Update update-readme.yaml

diff --git a/.github/workflows/update-readme.yaml b/.github/workflows/update-readme.yaml
--- a/.github/workflows/update-readme.yaml
+++ b/.github/workflows/update-readme.yaml
@@ -41,6 +41,10 @@ jobs:
           curl -v -o github_streak.svg https://github-readme-streak-stats.herokuapp.com/?user=0asaca0rum0&theme=radical
           if [ $? -ne 0 ]; then echo "Error fetching GitHub streak"; exit 1; fi
           
+          echo "Fetching GitHub trophies..."
+          curl -v -o github_trophies.svg https://github-profile-trophy.vercel.app/?username=0asaca0rum0&theme=radical&column=7
+          if [ $? -ne 0 ]; then echo "Error fetching GitHub trophies"; exit 1; fi
+          
           echo "Checking file sizes..."
           ls -l *.svg
           
@@ -48,15 +52,17 @@ jobs:
           head -n 5 github_stats.svg
           head -n 5 top_langs.svg
           head -n 5 github_streak.svg
+          head -n 5 github_trophies.svg
 
       - name: Commit and push if changed
+        env:
+          GH_TOKEN: ${{ secrets.GH_TOKEN }}
         run: |
           git config --global user.name 'github-actions[bot]'
           git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
-          git add github_stats.svg top_langs.svg github_streak.svg
-          git diff --staged --quiet || (git commit -m "Update README stats" && git push)
-        env:
-          GH_TOKEN: ${{ secrets.GH_TOKEN }}
+          git add github_stats.svg top_langs.svg github_streak.svg github_trophies.svg
+          git diff --staged --quiet || git commit -m "Update README stats"
+          git push https://${{ secrets.GH_TOKEN }}@github.com/0asaca0rum0/0asaca0rum0.git
 
       - name: Check for errors
         if: failure()
